version: "3"
services:
  plex:
    image: quay.io/linuxserver.io/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM=9-WdsC7QR9cd7bzo9xry
    volumes:
      - /media/volume/plex/config:/config
      - /media/volume/plex/data/temp:/data/temp
      - /media/volume/plex/transcode:/transcode
      - /media/Plex:/data/Plex
    devices:
      - "/dev/dri:/dev/dri"
    privileged: true
    restart: unless-stopped

  # tidal:
  #   build: 
  #     context: .
  #     dockerfile: tidal.Dockerfile
  #   container_name: tidal
  #   network_mode: host
  #   volumes:
  #     - ./downloads:/root/downloads
  #     - .tidal-dl.token.json:/root/.tidal-dl.token.json
  #     - .tidal-dl.json:/root/.tidal-dl.json