---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: home-server
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: plex
      volume: config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-temp-pvc
  namespace: home-server
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: plex
      volume: data-temp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-pvc
  namespace: home-server
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: plex
      volume: transcode
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: home-server
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: plex
      volume: media
